
export const projectsInfo= [
    {
        projectName : "Rocket Rider | Ride sharing app",
        id:1,
        image: "https://i.ibb.co/JzYpLgr/rider.png",
        features1: " User can take ride service. There are 4 service available ",
        features2: "Implemented google authentication. Any one can login by google login service",
        features3: "Private Route are implemented, without login no none don't access some pages",
        features4: "implemented google map, User can access location by using google map",
        liveLink: "https://rocket-ride.web.app/",
        githubLink:"https://github.com/FaazleRabbi/rocket-rider",
        projectCategory: 'react',
        technologyUsed: [
            "React.js",
            "Node.js",
            "Express.js",
            "MongoDB",
            "Firebase",
            "Bootstrap",
            "Stripe.js",
          ],
    },
    {
        projectName : "Fancy slider | slider maker app",
        id:2,
        image: "https://i.ibb.co/WgSrdKZ/slider.png",
        features1: " User can search pictures and select multi pictures to make slider ",
        features2: "User can unselect any of pictures that selected before",
        features3: "User can input slide duration ",
        features4: "Well control duration that user given before",
        liveLink: "https://faazlerabbi.github.io/fancy-slider/",
        githubLink:"https://github.com/FaazleRabbi/fancy-slider",
        projectCategory: 'react',
        technologyUsed: [
            "React.js",
            "Node.js",
            "Express.js",
            "MongoDB",
            "Firebase",
            "Bootstrap",
            "Stripe.js",
          ],
    },
    {
        projectName : "Logo service | Logo service app",
        id:3,
        image: "https://i.ibb.co/1n82GwJ/logo-Bekary.png",
        features1: " User can take get logo service. There are 3 service available. Admin can add service dynamically from admin panel,also delete any service any time ",
        features2: "Implemented google authentication. Any one can login by google login service",
        features3: "Private Route are implemented, without login no none don't access some pages",
        features4: "User can review of service that dynamically showed on website review section",
        liveLink: "https://logo-bakery.web.app/",
        githubLink:"https://github.com/FaazleRabbi/logo-service-client",
        projectCategory: 'react',
        technologyUsed: [
            "React.js",
            "Node.js",
            "Express.js",
            "MongoDB",
            "Firebase",
            "Bootstrap",
            "Stripe.js",
          ],
    }
]

